#!/bin/bash

# set aliases to create docker container for runing smrt
alias smrt="docker run -h docker-supersmart -v $PWD:/mydata docker-supersmart smrt $@"
alias smrt-utils='docker run -h docker-supersmart -v $PWD:/mydata docker-supersmart smrt-utils $@'
alias smrt-config='docker run -h docker-supersmart -v $PWD:/mydata docker-supersmart smrt-config $@'

echo '
   _____ _    _ _____  ______ _____    
  / ____| |  | |  __ \|  ____|  __ \   
 | (___ | |  | | |__) | |__  | |__) |  
  \___ \| |  | |  ___/|  __| |  _  /   
  ____) | |__| | |    | |____| | \ \   
 |_____/ \____/|_|    |______|_|__\_\_ 
  / ____|  \/  |   /\   |  __ \__   __|
 | (___ | \  / |  /  \  | |__) | | |   
  \___ \| |\/| | / /\ \ |  _  /  | |   
  ____) | |  | |/ ____ \| | \ \  | |   
 |_____/|_|  |_/_/    \_\_|  \_\ |_|   
'
echo "Welcome to the SUPERSMART pipeline developed by 
Naturalis Biodiversity Centre & Gothenburg University.

Available commands:

     smrt
     smrt-utils
     smrt-config 

To get started, try 'mysmrt --help' and visit www.supersmart-project.org.
"
